server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired


missyou:
  security:
    jwt-key: wab
    token-expired-in: 86400000
  order:
    max-sku-limit: 777
    pay-time-limit: 3600
